/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/+__root'
import { Route as LayoutImport } from './routes/+_layout'
import { Route as LayoutIndexImport } from './routes/+_layout/+index'
import { Route as LayoutInfoIndexImport } from './routes/+_layout/+info/+index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInfoIndexRoute = LayoutInfoIndexImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/info/': {
      id: '/_layout/info/'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof LayoutInfoIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutInfoIndexRoute: typeof LayoutInfoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutInfoIndexRoute: LayoutInfoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/info': typeof LayoutInfoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/info': typeof LayoutInfoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/info/': typeof LayoutInfoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/info'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info'
  id: '__root__' | '/_layout' | '/_layout/' | '/_layout/info/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "+__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "+_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/info/"
      ]
    },
    "/_layout/": {
      "filePath": "+_layout/+index.tsx",
      "parent": "/_layout"
    },
    "/_layout/info/": {
      "filePath": "+_layout/+info/+index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
