/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/+__root'
import { Route as IndexImport } from './routes/+index'
import { Route as InfoIndexImport } from './routes/+info/+index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InfoIndexRoute = InfoIndexImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/info/': {
      id: '/info/'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/info/': typeof InfoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info'
  id: '__root__' | '/' | '/info/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoIndexRoute: typeof InfoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoIndexRoute: InfoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "+__root.tsx",
      "children": [
        "/",
        "/info/"
      ]
    },
    "/": {
      "filePath": "+index.tsx"
    },
    "/info/": {
      "filePath": "+info/+index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
