/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FrequentlyDatasRemoveCommand } from '../models';
// @ts-ignore
import type { GetFrequentlyUsedDataOutputDto } from '../models';
// @ts-ignore
import type { GetFrequentlyUsedDataQuery } from '../models';
// @ts-ignore
import type { GetFrequentlyUsedSourcesOutputDto } from '../models';
// @ts-ignore
import type { IncreaseFrequentlyUsedDataUsageCommand } from '../models';
// @ts-ignore
import type { UpsertFrequentlyUsedDataCommand } from '../models';
// @ts-ignore
import type { UpsertFrequentlyUsedDataOutputDto } from '../models';
/**
* 
* @param {GetFrequentlyUsedDataQuery} [getFrequentlyUsedDataQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetDataPostParamCreator (getFrequentlyUsedDataQuery?: GetFrequentlyUsedDataQuery, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/FrequentlyUsedData/GetData`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(getFrequentlyUsedDataQuery, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetSourcesGetParamCreator (options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/FrequentlyUsedData/GetSources`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {IncreaseFrequentlyUsedDataUsageCommand} [increaseFrequentlyUsedDataUsageCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataIncreaseusagePostParamCreator (increaseFrequentlyUsedDataUsageCommand?: IncreaseFrequentlyUsedDataUsageCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/FrequentlyUsedData/increaseusage`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(increaseFrequentlyUsedDataUsageCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {FrequentlyDatasRemoveCommand} [frequentlyDatasRemoveCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataRemovePostParamCreator (frequentlyDatasRemoveCommand?: FrequentlyDatasRemoveCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/FrequentlyUsedData/remove`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(frequentlyDatasRemoveCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {UpsertFrequentlyUsedDataCommand} [upsertFrequentlyUsedDataCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataUpsertPostParamCreator (upsertFrequentlyUsedDataCommand?: UpsertFrequentlyUsedDataCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/FrequentlyUsedData/upsert`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(upsertFrequentlyUsedDataCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {GetFrequentlyUsedDataQuery} [getFrequentlyUsedDataQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetDataPostFp(getFrequentlyUsedDataQuery?: GetFrequentlyUsedDataQuery, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFrequentlyUsedDataOutputDto>> {
    const localVarAxiosArgs = await customerManagementFrequentlyUsedDataGetDataPostParamCreator(getFrequentlyUsedDataQuery, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['FrequentlyUsedDataApi.customerManagementFrequentlyUsedDataGetDataPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetSourcesGetFp(options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFrequentlyUsedSourcesOutputDto>> {
    const localVarAxiosArgs = await customerManagementFrequentlyUsedDataGetSourcesGetParamCreator(options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['FrequentlyUsedDataApi.customerManagementFrequentlyUsedDataGetSourcesGet']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {IncreaseFrequentlyUsedDataUsageCommand} [increaseFrequentlyUsedDataUsageCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataIncreaseusagePostFp(increaseFrequentlyUsedDataUsageCommand?: IncreaseFrequentlyUsedDataUsageCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementFrequentlyUsedDataIncreaseusagePostParamCreator(increaseFrequentlyUsedDataUsageCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['FrequentlyUsedDataApi.customerManagementFrequentlyUsedDataIncreaseusagePost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {FrequentlyDatasRemoveCommand} [frequentlyDatasRemoveCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataRemovePostFp(frequentlyDatasRemoveCommand?: FrequentlyDatasRemoveCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementFrequentlyUsedDataRemovePostParamCreator(frequentlyDatasRemoveCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['FrequentlyUsedDataApi.customerManagementFrequentlyUsedDataRemovePost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {UpsertFrequentlyUsedDataCommand} [upsertFrequentlyUsedDataCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataUpsertPostFp(upsertFrequentlyUsedDataCommand?: UpsertFrequentlyUsedDataCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpsertFrequentlyUsedDataOutputDto>> {
    const localVarAxiosArgs = await customerManagementFrequentlyUsedDataUpsertPostParamCreator(upsertFrequentlyUsedDataCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['FrequentlyUsedDataApi.customerManagementFrequentlyUsedDataUpsertPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {GetFrequentlyUsedDataQuery} [getFrequentlyUsedDataQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetDataPost(getFrequentlyUsedDataQuery?: GetFrequentlyUsedDataQuery, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementFrequentlyUsedDataGetDataPostFp(getFrequentlyUsedDataQuery, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataGetSourcesGet(options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementFrequentlyUsedDataGetSourcesGetFp(options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {IncreaseFrequentlyUsedDataUsageCommand} [increaseFrequentlyUsedDataUsageCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataIncreaseusagePost(increaseFrequentlyUsedDataUsageCommand?: IncreaseFrequentlyUsedDataUsageCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementFrequentlyUsedDataIncreaseusagePostFp(increaseFrequentlyUsedDataUsageCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {FrequentlyDatasRemoveCommand} [frequentlyDatasRemoveCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataRemovePost(frequentlyDatasRemoveCommand?: FrequentlyDatasRemoveCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementFrequentlyUsedDataRemovePostFp(frequentlyDatasRemoveCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {UpsertFrequentlyUsedDataCommand} [upsertFrequentlyUsedDataCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementFrequentlyUsedDataUpsertPost(upsertFrequentlyUsedDataCommand?: UpsertFrequentlyUsedDataCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementFrequentlyUsedDataUpsertPostFp(upsertFrequentlyUsedDataCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


