/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TokenOutputDto } from '../models';
/**
* 
* @param {string} email 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementNonAttendanceLoanGetloantokenEmailGetParamCreator (email: string, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    // verify required parameter 'email' is not null or undefined
    assertParamExists('customerManagementNonAttendanceLoanGetloantokenEmailGet', 'email', email)
    const localVarPath = `/customer-management/NonAttendanceLoan/getloantoken/{email}`
        .replace(`{${"email"}}`, encodeURIComponent(String(email)));
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {string} email 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementNonAttendanceLoanGetloantokenEmailGetFp(email: string, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenOutputDto>> {
    const localVarAxiosArgs = await customerManagementNonAttendanceLoanGetloantokenEmailGetParamCreator(email, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['NonAttendanceLoanApi.customerManagementNonAttendanceLoanGetloantokenEmailGet']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {string} email 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementNonAttendanceLoanGetloantokenEmailGet(email: string, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementNonAttendanceLoanGetloantokenEmailGetFp(email, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


