/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetScheduledTasksArchiveQuery } from '../models';
// @ts-ignore
import type { GetScheduledTasksQuery } from '../models';
// @ts-ignore
import type { ScheduledTaskArchiveOutputDto } from '../models';
// @ts-ignore
import type { ScheduledTaskOutputDto } from '../models';
/**
* 
* @param {GetScheduledTasksArchiveQuery} [getScheduledTasksArchiveQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetArchivePostParamCreator (getScheduledTasksArchiveQuery?: GetScheduledTasksArchiveQuery, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/ScheduledTask/getArchive`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(getScheduledTasksArchiveQuery, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {GetScheduledTasksQuery} [getScheduledTasksQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetPostParamCreator (getScheduledTasksQuery?: GetScheduledTasksQuery, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/ScheduledTask/get`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(getScheduledTasksQuery, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {GetScheduledTasksArchiveQuery} [getScheduledTasksArchiveQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetArchivePostFp(getScheduledTasksArchiveQuery?: GetScheduledTasksArchiveQuery, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ScheduledTaskArchiveOutputDto>>> {
    const localVarAxiosArgs = await customerManagementScheduledTaskGetArchivePostParamCreator(getScheduledTasksArchiveQuery, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['ScheduledTaskApi.customerManagementScheduledTaskGetArchivePost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {GetScheduledTasksQuery} [getScheduledTasksQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetPostFp(getScheduledTasksQuery?: GetScheduledTasksQuery, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ScheduledTaskOutputDto>>> {
    const localVarAxiosArgs = await customerManagementScheduledTaskGetPostParamCreator(getScheduledTasksQuery, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['ScheduledTaskApi.customerManagementScheduledTaskGetPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {GetScheduledTasksArchiveQuery} [getScheduledTasksArchiveQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetArchivePost(getScheduledTasksArchiveQuery?: GetScheduledTasksArchiveQuery, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementScheduledTaskGetArchivePostFp(getScheduledTasksArchiveQuery, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {GetScheduledTasksQuery} [getScheduledTasksQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementScheduledTaskGetPost(getScheduledTasksQuery?: GetScheduledTasksQuery, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementScheduledTaskGetPostFp(getScheduledTasksQuery, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


