/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddSettingDraftCommand } from '../models';
// @ts-ignore
import type { ApproveSettingDraftCommand } from '../models';
// @ts-ignore
import type { DeleteSettingDraftCommand } from '../models';
// @ts-ignore
import type { EditSettingDraftCommand } from '../models';
// @ts-ignore
import type { GetSettingDraftsDtoPagedListDto } from '../models';
// @ts-ignore
import type { GetSettingDraftsQuery } from '../models';
// @ts-ignore
import type { RejectSettingDraftCommand } from '../models';
/**
* 
* @param {AddSettingDraftCommand} [addSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsAddsettingdraftPostParamCreator (addSettingDraftCommand?: AddSettingDraftCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/addsettingdraft`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(addSettingDraftCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {ApproveSettingDraftCommand} [approveSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsApprovesettingdraftPostParamCreator (approveSettingDraftCommand?: ApproveSettingDraftCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/approvesettingdraft`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(approveSettingDraftCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {DeleteSettingDraftCommand} [deleteSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsDeletesettingdraftPostParamCreator (deleteSettingDraftCommand?: DeleteSettingDraftCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/deletesettingdraft`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(deleteSettingDraftCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {EditSettingDraftCommand} [editSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsEditsettingdraftPostParamCreator (editSettingDraftCommand?: EditSettingDraftCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/editsettingdraft`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(editSettingDraftCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {GetSettingDraftsQuery} [getSettingDraftsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsGetallsettingsPostParamCreator (getSettingDraftsQuery?: GetSettingDraftsQuery, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/getallsettings`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(getSettingDraftsQuery, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {RejectSettingDraftCommand} [rejectSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsRejectsettingdraftPostParamCreator (rejectSettingDraftCommand?: RejectSettingDraftCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/SettingDrafts/rejectsettingdraft`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(rejectSettingDraftCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {AddSettingDraftCommand} [addSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsAddsettingdraftPostFp(addSettingDraftCommand?: AddSettingDraftCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsAddsettingdraftPostParamCreator(addSettingDraftCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsAddsettingdraftPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {ApproveSettingDraftCommand} [approveSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsApprovesettingdraftPostFp(approveSettingDraftCommand?: ApproveSettingDraftCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsApprovesettingdraftPostParamCreator(approveSettingDraftCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsApprovesettingdraftPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {DeleteSettingDraftCommand} [deleteSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsDeletesettingdraftPostFp(deleteSettingDraftCommand?: DeleteSettingDraftCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsDeletesettingdraftPostParamCreator(deleteSettingDraftCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsDeletesettingdraftPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {EditSettingDraftCommand} [editSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsEditsettingdraftPostFp(editSettingDraftCommand?: EditSettingDraftCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsEditsettingdraftPostParamCreator(editSettingDraftCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsEditsettingdraftPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {GetSettingDraftsQuery} [getSettingDraftsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsGetallsettingsPostFp(getSettingDraftsQuery?: GetSettingDraftsQuery, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSettingDraftsDtoPagedListDto>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsGetallsettingsPostParamCreator(getSettingDraftsQuery, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsGetallsettingsPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {RejectSettingDraftCommand} [rejectSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsRejectsettingdraftPostFp(rejectSettingDraftCommand?: RejectSettingDraftCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingDraftsRejectsettingdraftPostParamCreator(rejectSettingDraftCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingDraftsApi.customerManagementSettingDraftsRejectsettingdraftPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {AddSettingDraftCommand} [addSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsAddsettingdraftPost(addSettingDraftCommand?: AddSettingDraftCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsAddsettingdraftPostFp(addSettingDraftCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {ApproveSettingDraftCommand} [approveSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsApprovesettingdraftPost(approveSettingDraftCommand?: ApproveSettingDraftCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsApprovesettingdraftPostFp(approveSettingDraftCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {DeleteSettingDraftCommand} [deleteSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsDeletesettingdraftPost(deleteSettingDraftCommand?: DeleteSettingDraftCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsDeletesettingdraftPostFp(deleteSettingDraftCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {EditSettingDraftCommand} [editSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsEditsettingdraftPost(editSettingDraftCommand?: EditSettingDraftCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsEditsettingdraftPostFp(editSettingDraftCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {GetSettingDraftsQuery} [getSettingDraftsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsGetallsettingsPost(getSettingDraftsQuery?: GetSettingDraftsQuery, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsGetallsettingsPostFp(getSettingDraftsQuery, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {RejectSettingDraftCommand} [rejectSettingDraftCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingDraftsRejectsettingdraftPost(rejectSettingDraftCommand?: RejectSettingDraftCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingDraftsRejectsettingdraftPostFp(rejectSettingDraftCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


