/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeleteSettingCommand } from '../models';
// @ts-ignore
import type { GetSettingDtoPagedListDto } from '../models';
// @ts-ignore
import type { GetSettingsQuery } from '../models';
// @ts-ignore
import type { UpsertSettingCommand } from '../models';
/**
* 
* @param {DeleteSettingCommand} [deleteSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsDeletePostParamCreator (deleteSettingCommand?: DeleteSettingCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/Settings/delete`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(deleteSettingCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {GetSettingsQuery} [getSettingsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsSettingsPostParamCreator (getSettingsQuery?: GetSettingsQuery, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/Settings/settings`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(getSettingsQuery, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {UpsertSettingCommand} [upsertSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsUpsertPostParamCreator (upsertSettingCommand?: UpsertSettingCommand, options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/Settings/upsert`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    localVarHeaderParameter['Content-Type'] = 'application/json';

    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
    localVarRequestOptions.data = serializeDataIfNeeded(upsertSettingCommand, localVarRequestOptions, configuration)

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {DeleteSettingCommand} [deleteSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsDeletePostFp(deleteSettingCommand?: DeleteSettingCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingsDeletePostParamCreator(deleteSettingCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingsApi.customerManagementSettingsDeletePost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {GetSettingsQuery} [getSettingsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsSettingsPostFp(getSettingsQuery?: GetSettingsQuery, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSettingDtoPagedListDto>> {
    const localVarAxiosArgs = await customerManagementSettingsSettingsPostParamCreator(getSettingsQuery, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingsApi.customerManagementSettingsSettingsPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {UpsertSettingCommand} [upsertSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsUpsertPostFp(upsertSettingCommand?: UpsertSettingCommand, options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
    const localVarAxiosArgs = await customerManagementSettingsUpsertPostParamCreator(upsertSettingCommand, options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['SettingsApi.customerManagementSettingsUpsertPost']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {DeleteSettingCommand} [deleteSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsDeletePost(deleteSettingCommand?: DeleteSettingCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingsDeletePostFp(deleteSettingCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {GetSettingsQuery} [getSettingsQuery] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsSettingsPost(getSettingsQuery?: GetSettingsQuery, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingsSettingsPostFp(getSettingsQuery, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {UpsertSettingCommand} [upsertSettingCommand] 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementSettingsUpsertPost(upsertSettingCommand?: UpsertSettingCommand, options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementSettingsUpsertPostFp(upsertSettingCommand, options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


