/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, DEFAULT_GLOBAL_CONFIG, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetHealthStatusOutputDto } from '../models';
/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersHealthstatusGetParamCreator (options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/Users/healthstatus`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersVersionGetParamCreator (options: RawAxiosRequestConfig = {}, configuration?: Configuration): Promise<RequestArgs> {
    const localVarPath = `/customer-management/Users/version`;
    // use dummy base URL string because the URL constructor only accepts absolute URLs.
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    // authentication Bearer required
    await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



    setSearchParams(localVarUrlObj, localVarQueryParameter);
    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
}


/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersHealthstatusGetFp(options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetHealthStatusOutputDto>> {
    const localVarAxiosArgs = await customerManagementUsersHealthstatusGetParamCreator(options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['UsersApi.customerManagementUsersHealthstatusGet']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersVersionGetFp(options?: RawAxiosRequestConfig, configuration?: Configuration): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
    const localVarAxiosArgs = await customerManagementUsersVersionGetParamCreator(options,configuration);
    const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
    const localVarOperationServerBasePath = operationServerMap['UsersApi.customerManagementUsersVersionGet']?.[localVarOperationServerIndex]?.url;
    return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
}




/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersHealthstatusGet(options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementUsersHealthstatusGetFp(options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}

/**
* 
* @param {*} [options] Override http request option.
* @throws {RequiredError}
*/
export async function customerManagementUsersVersionGet(options?: RawAxiosRequestConfig, configuration: Configuration = DEFAULT_GLOBAL_CONFIG) {
    return customerManagementUsersVersionGetFp(options, configuration).then((request) => request(configuration.axiosInstance, configuration.basePath));
}


