/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/ban-rule-api';
export * from './apis/city-api';
export * from './apis/customer-manager-api';
export * from './apis/frequently-used-data-api';
export * from './apis/non-attendance-loan-api';
export * from './apis/profile-api';
export * from './apis/scheduled-task-api';
export * from './apis/setting-drafts-api';
export * from './apis/settings-api';
export * from './apis/user-setting-api';
export * from './apis/users-api';
export * from './apis/virtual-customer-api';

