/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountOwnerDto } from './account-owner-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { AccountOwnershipTypeEnum } from './account-ownership-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationTypeEnum } from './relation-type-enum';

/**
 * 
 * @export
 * @interface AccountOutputDto
 */
export interface AccountOutputDto {
    /**
     * 
     * @type {number}
     * @memberof AccountOutputDto
     */
    'accountNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'accountTypeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'accountTypeCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'intCat'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'currencyType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'accountStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'accountStatusCode'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccountOutputDto
     */
    'isShared'?: boolean;
    /**
     * 
     * @type {Array<AccountOwnerDto>}
     * @memberof AccountOutputDto
     */
    'owners'?: Array<AccountOwnerDto> | null;
    /**
     * 
     * @type {string}
     * @memberof AccountOutputDto
     */
    'iban'?: string | null;
    /**
     * 
     * @type {RelationTypeEnum}
     * @memberof AccountOutputDto
     */
    'relationType'?: RelationTypeEnum;
    /**
     * 
     * @type {AccountOwnershipTypeEnum}
     * @memberof AccountOutputDto
     */
    'accountOwnershipType'?: AccountOwnershipTypeEnum;
}



