/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountOutputDto } from './account-output-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CardOutputDto } from './card-output-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { FacilityAccountOutputDto } from './facility-account-output-dto';

/**
 * 
 * @export
 * @interface AccountAndCardOutputDto
 */
export interface AccountAndCardOutputDto {
    /**
     * 
     * @type {Array<AccountOutputDto>}
     * @memberof AccountAndCardOutputDto
     */
    'accounts'?: Array<AccountOutputDto> | null;
    /**
     * 
     * @type {Array<CardOutputDto>}
     * @memberof AccountAndCardOutputDto
     */
    'cards'?: Array<CardOutputDto> | null;
    /**
     * 
     * @type {Array<FacilityAccountOutputDto>}
     * @memberof AccountAndCardOutputDto
     */
    'facilityAccounts'?: Array<FacilityAccountOutputDto> | null;
}

