/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountDto
 */
export interface AccountDto {
    /**
     * 
     * @type {number}
     * @memberof AccountDto
     */
    'accountNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    'lastUpdate'?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountDto
     */
    'counter'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountDto
     */
    'customerId'?: number;
}

