/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BanRuleActorLevelEnum } from './ban-rule-actor-level-enum';

/**
 * 
 * @export
 * @interface AddBanRuleActorLevelCommand
 */
export interface AddBanRuleActorLevelCommand {
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleActorLevelCommand
     */
    'username'?: string | null;
    /**
     * 
     * @type {BanRuleActorLevelEnum}
     * @memberof AddBanRuleActorLevelCommand
     */
    'actorLevel'?: BanRuleActorLevelEnum;
}



