/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RuleTypeEnum } from './rule-type-enum';

/**
 * 
 * @export
 * @interface AddBanRuleCommand
 */
export interface AddBanRuleCommand {
    /**
     * 
     * @type {RuleTypeEnum}
     * @memberof AddBanRuleCommand
     */
    'ruleType'?: RuleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'property'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'valueFrom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'valueTo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'end'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBanRuleCommand
     */
    'messageKey'?: string | null;
}



