/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CardOriginEnum } from './card-origin-enum';

/**
 * 
 * @export
 * @interface CardOutputDto
 */
export interface CardOutputDto {
    /**
     * 
     * @type {number}
     * @memberof CardOutputDto
     */
    'cardNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {CardOriginEnum}
     * @memberof CardOutputDto
     */
    'cardOrigin'?: CardOriginEnum;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'cardStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'cardStatusDesc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'cardType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardOutputDto
     */
    'cardTypeDesc'?: string | null;
}



