/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CardOriginEnum } from './card-origin-enum';

/**
 * 
 * @export
 * @interface CheckCardOutputDto
 */
export interface CheckCardOutputDto {
    /**
     * 
     * @type {boolean}
     * @memberof CheckCardOutputDto
     */
    'isCardRelated'?: boolean;
    /**
     * 
     * @type {CardOriginEnum}
     * @memberof CheckCardOutputDto
     */
    'cardOrigin'?: CardOriginEnum;
}



