/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChannelNameEnum } from './channel-name-enum';

/**
 * 
 * @export
 * @interface CheckCardQuery
 */
export interface CheckCardQuery {
    /**
     * 
     * @type {number}
     * @memberof CheckCardQuery
     */
    'customerNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckCardQuery
     */
    'cardNo'?: number;
    /**
     * 
     * @type {ChannelNameEnum}
     * @memberof CheckCardQuery
     */
    'channel'?: ChannelNameEnum;
}



