/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountConsiderDeleted } from './account-consider-deleted';
// May contain unused imports in some cases
// @ts-ignore
import type { ChannelNameEnum } from './channel-name-enum';

/**
 * 
 * @export
 * @interface CheckAccountQuery
 */
export interface CheckAccountQuery {
    /**
     * 
     * @type {number}
     * @memberof CheckAccountQuery
     */
    'customerNo'?: number;
    /**
     * 
     * @type {ChannelNameEnum}
     * @memberof CheckAccountQuery
     */
    'channel'?: ChannelNameEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof CheckAccountQuery
     */
    'accounts'?: Array<number> | null;
    /**
     * 
     * @type {Array<AccountConsiderDeleted>}
     * @memberof CheckAccountQuery
     */
    'accountConsiderDeleteds'?: Array<AccountConsiderDeleted> | null;
}



