/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerStatusCodeEnum } from './customer-status-code-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { EconomicCodeEnum } from './economic-code-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { ForeignIdTypeEnum } from './foreign-id-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { GenderEnum } from './gender-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { HomeOwnerShipEnum } from './home-owner-ship-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { IVRFlagEnum } from './ivrflag-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { IdTypeEnum } from './id-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { LockerHolderEnum } from './locker-holder-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { MaritalStatusEnum } from './marital-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { NationalityCodeEnum } from './nationality-code-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { TFNProvidedEnum } from './tfnprovided-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { VipCustomerEnum } from './vip-customer-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { WithholdingTaxExeptionEnum } from './withholding-tax-exeption-enum';

/**
 * 
 * @export
 * @interface CreateCustomerCommand
 */
export interface CreateCustomerCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'alley'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'street'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'village'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'cityCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'tellNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'faxNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'homeTel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'mobNo'?: string | null;
    /**
     * 
     * @type {NationalityCodeEnum}
     * @memberof CreateCustomerCommand
     */
    'nationalityCode'?: NationalityCodeEnum;
    /**
     * 
     * @type {HomeOwnerShipEnum}
     * @memberof CreateCustomerCommand
     */
    'homeOwnership'?: HomeOwnerShipEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'jobDetailCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'idNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'issueDate'?: string | null;
    /**
     * 
     * @type {IdTypeEnum}
     * @memberof CreateCustomerCommand
     */
    'idType'?: IdTypeEnum;
    /**
     * 
     * @type {VipCustomerEnum}
     * @memberof CreateCustomerCommand
     */
    'vipCustomer'?: VipCustomerEnum;
    /**
     * 
     * @type {CustomerStatusCodeEnum}
     * @memberof CreateCustomerCommand
     */
    'status'?: CustomerStatusCodeEnum;
    /**
     * 
     * @type {LockerHolderEnum}
     * @memberof CreateCustomerCommand
     */
    'lockerHolder'?: LockerHolderEnum;
    /**
     * 
     * @type {TFNProvidedEnum}
     * @memberof CreateCustomerCommand
     */
    'tfnProvided'?: TFNProvidedEnum;
    /**
     * 
     * @type {EconomicCodeEnum}
     * @memberof CreateCustomerCommand
     */
    'group_AffliateCode'?: EconomicCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'birthCertificateIssuingPlaceCode'?: string | null;
    /**
     * 
     * @type {WithholdingTaxExeptionEnum}
     * @memberof CreateCustomerCommand
     */
    'withholdingTaxExeption'?: WithholdingTaxExeptionEnum;
    /**
     * 
     * @type {IVRFlagEnum}
     * @memberof CreateCustomerCommand
     */
    'ivrFlag'?: IVRFlagEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'fatherName'?: string | null;
    /**
     * 
     * @type {ForeignIdTypeEnum}
     * @memberof CreateCustomerCommand
     */
    'foreignIDType'?: ForeignIdTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'trackingNo'?: string | null;
    /**
     * 
     * @type {GenderEnum}
     * @memberof CreateCustomerCommand
     */
    'gender'?: GenderEnum;
    /**
     * 
     * @type {MaritalStatusEnum}
     * @memberof CreateCustomerCommand
     */
    'maritalStatus'?: MaritalStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'idNo_PasportNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'idSerialNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'idSeries'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'idSeriesHarf'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomerCommand
     */
    'desiredHomeBranch'?: string | null;
}



