/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerInfoOutputDto } from './customer-info-output-dto';

/**
 * 
 * @export
 * @interface CusRelateToAccOutputDto
 */
export interface CusRelateToAccOutputDto {
    /**
     * 
     * @type {number}
     * @memberof CusRelateToAccOutputDto
     */
    'accountNo'?: number;
    /**
     * 
     * @type {Array<CustomerInfoOutputDto>}
     * @memberof CusRelateToAccOutputDto
     */
    'customers'?: Array<CustomerInfoOutputDto> | null;
}

