/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerAccountByCifFromMainMachineOutputDto
 */
export interface CustomerAccountByCifFromMainMachineOutputDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'acc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'openStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'cheqbookF'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'cardF'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'accClass'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'accTypeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'currency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'isJoined'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'accType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerAccountByCifFromMainMachineOutputDto
     */
    'accSubType'?: string | null;
}

