/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChannelNameEnum } from './channel-name-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { OSTypeEnum } from './ostype-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLevelEnum } from './user-level-enum';

/**
 * 
 * @export
 * @interface CustomerDeviceDto
 */
export interface CustomerDeviceDto {
    /**
     * 
     * @type {UserLevelEnum}
     * @memberof CustomerDeviceDto
     */
    'userLevel'?: UserLevelEnum;
    /**
     * 
     * @type {ChannelNameEnum}
     * @memberof CustomerDeviceDto
     */
    'channel'?: ChannelNameEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomerDeviceDto
     */
    'deviceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDeviceDto
     */
    'osVersion'?: string | null;
    /**
     * 
     * @type {OSTypeEnum}
     * @memberof CustomerDeviceDto
     */
    'osType'?: OSTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CustomerDeviceDto
     */
    'customerId'?: number;
}



