/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerTotalInfoOutputDto
 */
export interface CustomerTotalInfoOutputDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'customerNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'shahabNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'customerType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'fatherName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'customerPostalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'customerTel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'idNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'certificateId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'bornDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'provinceCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'idType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'shahabStat'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'customerStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'identityIssuePlace'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'identityIssueDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerTotalInfoOutputDto
     */
    'phoneNoRes'?: string | null;
}

