/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountDto } from './account-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CardDto } from './card-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerDeviceDto } from './customer-device-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { FacilityAccountDto } from './facility-account-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonTypeEnum } from './person-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RelatedAccountDto } from './related-account-dto';

/**
 * 
 * @export
 * @interface CustomerDetailOutputDto
 */
export interface CustomerDetailOutputDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'mobileNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'nationalCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailOutputDto
     */
    'customerNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailOutputDto
     */
    'shahabNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {PersonTypeEnum}
     * @memberof CustomerDetailOutputDto
     */
    'customerType'?: PersonTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailOutputDto
     */
    'hashCode'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerDetailOutputDto
     */
    'shahkarConfirm'?: boolean;
    /**
     * 
     * @type {Array<AccountDto>}
     * @memberof CustomerDetailOutputDto
     */
    'accounts'?: Array<AccountDto> | null;
    /**
     * 
     * @type {Array<CardDto>}
     * @memberof CustomerDetailOutputDto
     */
    'cards'?: Array<CardDto> | null;
    /**
     * 
     * @type {Array<FacilityAccountDto>}
     * @memberof CustomerDetailOutputDto
     */
    'facilityAccounts'?: Array<FacilityAccountDto> | null;
    /**
     * 
     * @type {Array<CustomerDeviceDto>}
     * @memberof CustomerDetailOutputDto
     */
    'devices'?: Array<CustomerDeviceDto> | null;
    /**
     * 
     * @type {Array<RelatedAccountDto>}
     * @memberof CustomerDetailOutputDto
     */
    'relatedAccounts'?: Array<RelatedAccountDto> | null;
}



