/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonTypeEnum } from './person-type-enum';

/**
 * 
 * @export
 * @interface CustomerOutputDto
 */
export interface CustomerOutputDto {
    /**
     * 
     * @type {number}
     * @memberof CustomerOutputDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'mobileNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'nationalCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerOutputDto
     */
    'customerNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerOutputDto
     */
    'shahabNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {PersonTypeEnum}
     * @memberof CustomerOutputDto
     */
    'customerType'?: PersonTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'hashCode'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerOutputDto
     */
    'shahkarConfirm'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'createdUtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerOutputDto
     */
    'lastModifiedUtc'?: string | null;
}



