/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerInfoOutputDto
 */
export interface CustomerInfoOutputDto {
    /**
     * 
     * @type {number}
     * @memberof CustomerInfoOutputDto
     */
    'customerNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'customerType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'mobileNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'nationalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'idType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'shahabNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfoOutputDto
     */
    'birthDate'?: string | null;
}

