/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FacilityRelationTypeEnum } from './facility-relation-type-enum';

/**
 * 
 * @export
 * @interface FacilityAccountDto
 */
export interface FacilityAccountDto {
    /**
     * 
     * @type {number}
     * @memberof FacilityAccountDto
     */
    'accountNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'openStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'accountTypeCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'accountTypeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'currencyType'?: string | null;
    /**
     * 
     * @type {FacilityRelationTypeEnum}
     * @memberof FacilityAccountDto
     */
    'facilityType'?: FacilityRelationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'accountSubType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FacilityAccountDto
     */
    'lastUpdate'?: string;
    /**
     * 
     * @type {number}
     * @memberof FacilityAccountDto
     */
    'counter'?: number;
    /**
     * 
     * @type {number}
     * @memberof FacilityAccountDto
     */
    'customerId'?: number;
}



