/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetHealthStatusOutputDto
 */
export interface GetHealthStatusOutputDto {
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'readDatabaseOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'readDatabaseTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'writeDatabaseOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'writeDatabaseTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'readRedisOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'readRedisTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'writeRedisOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'writeRedisTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'removeRedisOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'removeRedisTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'channelOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'channelTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'identityOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'identityTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'cardOperationsOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'cardOperationsTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'otpManagementOK'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatusOutputDto
     */
    'otpManagementTime'?: number;
}

