/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QueryBuilderFilterRule } from './query-builder-filter-rule';

/**
 * 
 * @export
 * @interface GetScheduledTasksArchiveQuery
 */
export interface GetScheduledTasksArchiveQuery {
    /**
     * 
     * @type {QueryBuilderFilterRule}
     * @memberof GetScheduledTasksArchiveQuery
     */
    'filter'?: QueryBuilderFilterRule;
    /**
     * 
     * @type {string}
     * @memberof GetScheduledTasksArchiveQuery
     */
    'sort'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetScheduledTasksArchiveQuery
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetScheduledTasksArchiveQuery
     */
    'pageSize'?: number;
}

