/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetFrequentlyUsedData } from './get-frequently-used-data';

/**
 * 
 * @export
 * @interface GetFrequentlyUsedDataOutputDto
 */
export interface GetFrequentlyUsedDataOutputDto {
    /**
     * 
     * @type {Array<GetFrequentlyUsedData>}
     * @memberof GetFrequentlyUsedDataOutputDto
     */
    'upsertedData'?: Array<GetFrequentlyUsedData> | null;
    /**
     * 
     * @type {Array<GetFrequentlyUsedData>}
     * @memberof GetFrequentlyUsedDataOutputDto
     */
    'deletedData'?: Array<GetFrequentlyUsedData> | null;
    /**
     * 
     * @type {string}
     * @memberof GetFrequentlyUsedDataOutputDto
     */
    'token'?: string | null;
}

