/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActionTypeEnum } from './action-type-enum';

/**
 * 
 * @export
 * @interface GetSettingDraftsDto
 */
export interface GetSettingDraftsDto {
    /**
     * 
     * @type {number}
     * @memberof GetSettingDraftsDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSettingDraftsDto
     */
    'key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSettingDraftsDto
     */
    'value'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetSettingDraftsDto
     */
    'isAppSetting'?: boolean;
    /**
     * 
     * @type {ActionTypeEnum}
     * @memberof GetSettingDraftsDto
     */
    'actionType'?: ActionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof GetSettingDraftsDto
     */
    'createdById'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetSettingDraftsDto
     */
    'createdUtc'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSettingDraftsDto
     */
    'lastModifiedById'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetSettingDraftsDto
     */
    'lastModifiedUtc'?: string | null;
}



