/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BanRuleActorLevelEnum } from './ban-rule-actor-level-enum';

/**
 * 
 * @export
 * @interface GetBanRulePersonsOutputDto
 */
export interface GetBanRulePersonsOutputDto {
    /**
     * 
     * @type {number}
     * @memberof GetBanRulePersonsOutputDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'nationalID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'startTimeUtc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'endTimeUtc'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetBanRulePersonsOutputDto
     */
    'isDeleted'?: boolean;
    /**
     * 
     * @type {BanRuleActorLevelEnum}
     * @memberof GetBanRulePersonsOutputDto
     */
    'banRuleActorLevel'?: BanRuleActorLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'deleteDescription'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetBanRulePersonsOutputDto
     */
    'createdById'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'createdUtc'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetBanRulePersonsOutputDto
     */
    'lastModifiedById'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBanRulePersonsOutputDto
     */
    'lastModifiedUtc'?: string | null;
}



