/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetBanRulePersonsOutputDto } from './get-ban-rule-persons-output-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PagedListMetaData } from './paged-list-meta-data';

/**
 * 
 * @export
 * @interface GetBanRulePersonsOutputDtoPagedListDto
 */
export interface GetBanRulePersonsOutputDtoPagedListDto {
    /**
     * 
     * @type {Array<GetBanRulePersonsOutputDto>}
     * @memberof GetBanRulePersonsOutputDtoPagedListDto
     */
    'items'?: Array<GetBanRulePersonsOutputDto> | null;
    /**
     * 
     * @type {PagedListMetaData}
     * @memberof GetBanRulePersonsOutputDtoPagedListDto
     */
    'metaData'?: PagedListMetaData;
}

