/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChannelNameEnum } from './channel-name-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { FrequentlyDataUsedCategory } from './frequently-data-used-category';

/**
 * 
 * @export
 * @interface IncreaseFrequentlyUsedDataUsageCommand
 */
export interface IncreaseFrequentlyUsedDataUsageCommand {
    /**
     * 
     * @type {FrequentlyDataUsedCategory}
     * @memberof IncreaseFrequentlyUsedDataUsageCommand
     */
    'category'?: FrequentlyDataUsedCategory;
    /**
     * 
     * @type {number}
     * @memberof IncreaseFrequentlyUsedDataUsageCommand
     */
    'userId'?: number;
    /**
     * 
     * @type {ChannelNameEnum}
     * @memberof IncreaseFrequentlyUsedDataUsageCommand
     */
    'channel'?: ChannelNameEnum;
    /**
     * 
     * @type {string}
     * @memberof IncreaseFrequentlyUsedDataUsageCommand
     */
    'value'?: string | null;
}



