/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IsLegalRelatedCustomerRelationExistQuery
 */
export interface IsLegalRelatedCustomerRelationExistQuery {
    /**
     * 
     * @type {number}
     * @memberof IsLegalRelatedCustomerRelationExistQuery
     */
    'signGrantedCustomerNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof IsLegalRelatedCustomerRelationExistQuery
     */
    'legalRelatedCustomerNumber'?: number;
}

