/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OnlineAccountOutputDto
 */
export interface OnlineAccountOutputDto {
    /**
     * 
     * @type {number}
     * @memberof OnlineAccountOutputDto
     */
    'accountNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof OnlineAccountOutputDto
     */
    'customerNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'ownPercent'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'accountTypeCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'currencyType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'accountStatusCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'intCat'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OnlineAccountOutputDto
     */
    'accountTypeName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OnlineAccountOutputDto
     */
    'ownersCount'?: number;
}

