/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PagedListMetaData
 */
export interface PagedListMetaData {
    /**
     * 
     * @type {number}
     * @memberof PagedListMetaData
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListMetaData
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListMetaData
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedListMetaData
     */
    'totalCount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListMetaData
     */
    'hasPrevious'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListMetaData
     */
    'hasNext'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedListMetaData
     */
    'hasPages'?: boolean;
}

