/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SendOTPTypeEnum } from './send-otptype-enum';

/**
 * 
 * @export
 * @interface PreRegisterOutputDto
 */
export interface PreRegisterOutputDto {
    /**
     * 
     * @type {number}
     * @memberof PreRegisterOutputDto
     */
    'lifeTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof PreRegisterOutputDto
     */
    'codeLength'?: number;
    /**
     * 
     * @type {string}
     * @memberof PreRegisterOutputDto
     */
    'message'?: string | null;
    /**
     * 
     * @type {SendOTPTypeEnum}
     * @memberof PreRegisterOutputDto
     */
    'otpType'?: SendOTPTypeEnum;
}



