/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PreRegisterCommand
 */
export interface PreRegisterCommand {
    /**
     * 
     * @type {string}
     * @memberof PreRegisterCommand
     */
    'accOrCifNum'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PreRegisterCommand
     */
    'nationalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PreRegisterCommand
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PreRegisterCommand
     */
    'smsHashCode'?: string | null;
}

