/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QueryBuilderFilterRule
 */
export interface QueryBuilderFilterRule {
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'condition'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'field'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'input'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'operator'?: string | null;
    /**
     * 
     * @type {Array<QueryBuilderFilterRule>}
     * @memberof QueryBuilderFilterRule
     */
    'rules'?: Array<QueryBuilderFilterRule> | null;
    /**
     * 
     * @type {string}
     * @memberof QueryBuilderFilterRule
     */
    'type'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryBuilderFilterRule
     */
    'value'?: Array<string> | null;
}

