/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelationStatusEnum } from './relation-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationTypeEnum } from './relation-type-enum';

/**
 * 
 * @export
 * @interface RelatedAccountDto
 */
export interface RelatedAccountDto {
    /**
     * 
     * @type {number}
     * @memberof RelatedAccountDto
     */
    'accountNumber'?: number;
    /**
     * 
     * @type {RelationTypeEnum}
     * @memberof RelatedAccountDto
     */
    'relationType'?: RelationTypeEnum;
    /**
     * 
     * @type {RelationStatusEnum}
     * @memberof RelatedAccountDto
     */
    'status'?: RelationStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof RelatedAccountDto
     */
    'percent'?: number;
    /**
     * 
     * @type {string}
     * @memberof RelatedAccountDto
     */
    'startDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedAccountDto
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedAccountDto
     */
    'lastUpdate'?: string;
    /**
     * 
     * @type {number}
     * @memberof RelatedAccountDto
     */
    'counter'?: number;
    /**
     * 
     * @type {number}
     * @memberof RelatedAccountDto
     */
    'customerId'?: number;
}



