/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export const RelationStatusEnum = {
    NUMBER_0: 0,
    NUMBER_9: 9
} as const;

export type RelationStatusEnum = typeof RelationStatusEnum[keyof typeof RelationStatusEnum];



