/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequestUpgradeForLevelTwoOutputDto
 */
export interface RequestUpgradeForLevelTwoOutputDto {
    /**
     * 
     * @type {string}
     * @memberof RequestUpgradeForLevelTwoOutputDto
     */
    'message'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RequestUpgradeForLevelTwoOutputDto
     */
    'lifeTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUpgradeForLevelTwoOutputDto
     */
    'codeLength'?: number;
}

