/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SabtAhvalInquiryOutputDto
 */
export interface SabtAhvalInquiryOutputDto {
    /**
     * 
     * @type {string}
     * @memberof SabtAhvalInquiryOutputDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SabtAhvalInquiryOutputDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SabtAhvalInquiryOutputDto
     */
    'deathStatus'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SabtAhvalInquiryOutputDto
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SabtAhvalInquiryOutputDto
     */
    'deathDate'?: string | null;
}

