/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScheduledTaskArchiveOutputDto
 */
export interface ScheduledTaskArchiveOutputDto {
    /**
     * 
     * @type {string}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'commandName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'fixedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'response'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'hasError'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'executionTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ScheduledTaskArchiveOutputDto
     */
    'executionDuration'?: number;
}

