/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBanRuleCommand
 */
export interface UpdateBanRuleCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateBanRuleCommand
     */
    'banRuleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'valueFrom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'valueTo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'end'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBanRuleCommand
     */
    'messageKey'?: string | null;
}

