/* tslint:disable */
/* eslint-disable */
/**
 * WebAppBlazor.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FrequentlyDataUsedCategory } from './frequently-data-used-category';

/**
 * 
 * @export
 * @interface UpsertFrequentlyUsedDataCommand
 */
export interface UpsertFrequentlyUsedDataCommand {
    /**
     * 
     * @type {FrequentlyDataUsedCategory}
     * @memberof UpsertFrequentlyUsedDataCommand
     */
    'category'?: FrequentlyDataUsedCategory;
    /**
     * 
     * @type {string}
     * @memberof UpsertFrequentlyUsedDataCommand
     */
    'value'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFrequentlyUsedDataCommand
     */
    'title'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpsertFrequentlyUsedDataCommand
     */
    'forAll'?: boolean;
}



