name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.0.x"
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Format
        if: (${{ success() }} || ${{ failure() }}) # ensures this step runs even if previous steps fail
        run: pnpm run format && { [ "`git status --porcelain=v1`" == "" ] || (echo "please run pnpm run format locally and push your changes"; git diff; exit 1); }

  Test:
    env:
      MICRO_IFRAME_ID: baran-playground-testid
      MICRO_PORT: 5155
      MICRO_USERNAME: "-"
      MICRO_PASSWORD: "-"
      MICRO_ENV: production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.0.x"
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm playwright install chromium

      - name: Build
        run: pnpm run build

      - name: Run Tests
        run: |
          pnpm run test:unit 
          pnpm run test:integration
